version: "3.8"

services:
  be_app:
    build:
      context: .
      dockerfile: dockerfiles/backend.dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - app-network
    platform: linux/amd64
  
  fe_app:
    build:
      context: .
      dockerfile: dockerfiles/frontend.dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    platform: linux/amd64

  # nginx:
  #   image: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - be_app
  #   networks:
  #     - app-network
  #   platform: linux/amd64

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    env_file:
      - ./payment-search-tool-api/.env
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
    platform: linux/amd64


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin"
    restart: always
    ports:
      - 9090:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - app-network
    platform: linux/amd64

#Volumes
volumes:
  dbdata:
    driver: local

#Docker Networks
networks:
  app-network:
    driver: bridge


